name: test
uid: uuid-of-etcd-resource
serviceName: test
configMapName: test

#priorityClassName: foo

tlsServerSecret: etcd-server-tls
tlsClientSecret: etcd-client-tls
tlsCASecret: ca-etcd
annotations: {}
labels: {}

etcd:
  replicas: 1
  enableTLS: false
  pullPolicy: IfNotPresent
  metrics: basic
  clientPort: 2379
  serverPort: 2380
  resources:
    limits:
      cpu: 100m
      memory: 512Gi
    requests:
      cpu: 50m
      memory: 128Mi
  quota: 8000000000
  #username: username
  #password: password

backup:
  pullPolicy: IfNotPresent
  etcdConnectionTimeout: 5m
  garbageCollectionPolicy: LimitBased
  maxBackups: 7
  resources:
    limits:
      cpu: 100m
      memory: 512Gi
    requests:
      cpu: 50m
      memory: 128Mi

volumeClaimTemplateName: test
storageClass: ""
storageCapacity: 16Gi

store:
  storageProvider: ""
  storePrefix: ""
  storageContainer: ""
